baseURL = "https://wsdookadr.github.io/"
languageCode = "en"

title = "Blog"
theme = "antora"

copyright = ""
paginate = 3

[params]
  description = "t123"
  keywords = ["consulting","consultant","software","freelance","databases","math","opensource"]
# editThisPage = "https://github.com/basil/antora-default-ui-hugo-theme/edit/master/exampleSite/content/"
  since = 2015

[markup]
  [markup.asciidocext]
    [markup.asciidocext.attributes]
      "icons" = "font"
      "source-highlighter" = "highlightjs"
  [markup.highlight]
    # Disable Goldmark Chroma syntax highlighter
    codeFences = false

[taxonomies]
    tag = "tags"
    category = "categories"
