+++
title = "Fast sub-tree containment checks"
date = "2021-02-21"
markup = "asciidoc"
tags = ["algorithms","data-structures"]
+++

:pygments-css: style

++++
<div></div>
++++

++++
include::layouts/partials/mathjax.html[]
++++


There's a problem on leetcode called link:https://leetcode.com/problems/subtree-of-another-tree/["Subtree of Another tree"].
It requires to check whether one binary tree is a subtree of another binary tree.

There are two official solutions presented, one involving a link:https://en.wikipedia.org/wiki/Tree_traversal#Pre-order[pre-order traversal] which is 
+++$O(m^2 + n^2+m\cdot n)$+++ and another one
that checks does a traversal for every subtree of the bigger tree, and checks if it's equal
to the smaller tree, element-by-element and this is +++$O(m\cdot n)$+++.

It's possible to write a different solution using
link:https://en.wikipedia.org/wiki/Merkle_tree[Merkle trees] that has
+++$O(m+n)$+++ link:https://en.wikipedia.org/wiki/Time_complexity[time complexity] (if we consider +++$O(1)$+++ the time to compute one hash).

The Merkle trees can be computed
link:https://en.wikipedia.org/wiki/Top-down_and_bottom-up_design[bottom-up]
and the hashes for each node can be stored. Then the containment check
only requires checking if a certain hash is present in a dictionary.

[NOTE]
This will pass all the tests, but if we want to avoid false positives
completely, once a hash match is found we need to do one tree-equality check.
Merkle trees can generate link:https://stackoverflow.com/a/14197504/827519[false positives] 
because link:https://en.wikipedia.org/wiki/Collision_(computer_science)[hash collisions] are possible.

[source%linenums,python]
----
include::content/posts/p3-code1.py[indent=1]
----

include::layouts/partials/promo-opt.adoc[]

